repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        name: Trailing spaces check
      - id: end-of-file-fixer
        name: EOF character check
      - id: check-yaml
        name: Yaml format check

  - repo: local
    hooks:
      - id: gdformat
        name: Gdscript format check
        entry: gdformat
        language: system
        types: [file]
        files: '\.gd$'
      - id: conventional-commit
        name: Enforcing conventional commit
        entry: .githooks/commit-msg-check
        language: script
        stages: [commit-msg]
