repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        name: Trailing spaces check
        description: Trims trailing whitespace.

      - id: end-of-file-fixer
        name: EOF character check
        description: Fixes EOF character.

      - id: check-yaml
        name: Yaml format check
        description: Enforce yaml files format.

  - repo: local
    hooks:
      - id: gdformat
        name: Gdscript format check
        description: Enforce gdscript files format.
        entry: gdformat
        language: system
        types: [file]
        files: '\.gd$'

      - id: conventional-commit
        name: Enforcing conventional commit
        description: Checks commit message to enforce conventional commit messages.
        entry: .githooks/commit-msg-check
        language: script
        stages: [commit-msg]
